version: '3.7'

services:
  db:
    image: mariadb:10.2.40-bionic
    #restart: always
    container_name: sha-task-db
    command: mysqld --sql_mode=""
    ports:
      - "3312:3306"
    environment:
      MARIADB_DATABASE: sha-task
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - ./db:/var/lib/mysql

  app:
    build:
      context: .docker
    container_name: sha-task
    ports:
      - "82:80"
    volumes:
      - ./:/var/www/html
    links:
      - db
    
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    #restart: always
    container_name: sha-task-phpmyadmin
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 10000M